POST http://localhost:8080/experience/make-post
Content-Type: application/json

{
		"title": "Snake Farm Tour",
		"description": "See snakes in their natural habitat",
		"streetAddress": "3800 Walnut Street",
		"cityAddress": "Philadelphia",
		"stateAddress": "PA",
		"zipAddress": "19104",
		"timeStart": "Tue Feb 01 2022 00:00:00 GMT+0000 (GMT)",
		"timeEnd": "Wed Feb 02 2022 00:00:00 GMT+0000 (GMT)",
		"price": "50",
		"tags": "party, fun, concert",
		"hostEmail": "kragula@seas.upenn.edu"
}